# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Sixty Meters"

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: "Theo's personal blog about tech, life and everything else.."

# Tagline below the site title
tagline: "my alternative to /dev/null"

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://sixtymeters.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: Archive
  url: /tags/
- text: About Me
  url: https://theowinter.ch

# The shortname for your Disqus site to enable comments.
disqus: theowinterch

# Author information - author info at the bottom of the post
author_name: "Theo Winter"
author_bio: "Hi I'm Theo. A swiss coder, traveller and photography hobbyist. I've studied Computer Science at <a href='https://www.hsr.ch'>HSR</a> and am now working on cool projects for <a href='https://twitter.com/zuehlke_group'>@Zuehlke Engineering</a>."
author_url: "https://theowinter.ch"
author_location: "Zürich, Switzerland"
author_image: authorimage.jpg



# Footer ad banner
banner_url: ""
banner_image: 

# Footer newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: 

# Social links in the site footer
twitter_username: "TheodorWinter"
facebook_username: 
googleplus_username: "+TheoWinterCH"
github_username: "aerobless"
codepen_username: 
dribbble_username: 
medium_username:
instagram_username: "aerobless"
pinterest_username:
linkedin_username: "theodorwinter"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
